def rules():
    print("Check in and out Time::")
    print("Check-in time : 12:00 noon")
    print("Check-out time : 10:00 morning")
    print("Pets not allowed")
    print("\nParking:")
    print("Parking, Free parking, On-site parking(reservation is not needed), Private parking")
    print("\nAccommodation:")
    print("""For your cozy accommodation is offered only one room type - double in the farm stay. 
    For guests are provided facilities such as telephone, air conditioning, kitchenette, spa bath, refrigerator, desk, free toiletries.""")
    print("The apartment is soundproofing.")
    print("Accommodation has a lot of rooms with garden view, pool view, mountain view, landmark view.")
    print("For guests is provided special facilities: fireplace.")
    print("On our website, you can book Farm stay Vasu Farm Sasan Gir in no time. The offered prices are minimal and there are no fees during the payment for the reservation.")
    print("\nCommon Area:")
    print("Garden")
    print("\nRestaurant:")
    print("Available for Family and Group together.")